/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef broxy_CONSTANTS_H
#define broxy_CONSTANTS_H

#include "broxy_types.h"

namespace broxy {

class broxyConstants {
 public:
  broxyConstants();

};

extern const broxyConstants g_broxy_constants;

} // namespace

#endif
