/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "../src/broxy_constants.h"

namespace broxy {

const broxyConstants g_broxy_constants;

broxyConstants::broxyConstants() {
}

} // namespace

